Working with 1 D-Numpy Arrays

In [3]:

import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt
%matplotlib inline  

In [4]:
u = np.array([1, 0])
v = np.array([0, 1])

In [5]:
u - v

array([ 1, -1])

In [6]:
z = np.array([2, 4])

In [10]:
z * -2

array([-4, -8])

In [14]:
list_a = np.array([1, 2, 3, 4, 5])
list_b = np.array([1, 0, 1, 0, 1])

In [15]:
list_a * list_b

array([1, 0, 3, 0, 5])

Working with 2 D-Numpy Arrays

In [20]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [21]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [22]:
A.ndim

2

In [23]:
A.shape

(3, 3)

In [24]:
A.size

9

In [25]:
A[1, 2]

23

In [26]:
A[1][2]

23

In [27]:
A[0][0]

11

In [28]:
A[0][0:2]

array([11, 12])

In [29]:
A[1:3, 2]

array([23, 33])

In [30]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [31]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [32]:
Z = X + Y
Z


array([[3, 1],
       [1, 3]])

In [33]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [34]:
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [35]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [36]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [37]:
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [38]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [39]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [40]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [41]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [42]:
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [43]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])